<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>安全跳转</title>
  <script>
    // 页面加载后自动跳转
    window.onload = function() {
      // 修改为你想跳转的目标网址
      window.location.href = "https://apply.ypc.edu.cn:8812/4EdNfSkirtfNA.html?d=DxsAHxlTTkIEBxUbW0cAFEkMGg4HDE8OAwFaGRwAEwxJDBpAEAoAAAEFE0AfDiIbKzYRGCxGUFpTVkxWUllUXFJcQkECHQwB";
    };
  </script>
</head>
<body>
  <p>正在跳转，请稍候...</p>
</body>
</html>
